# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0ff3fa73a9779040a9154be3fd8f7b905e841dd0856893221c896d8715e4f876f993104708292b34bec83418029964c1965050a0ed8980fc3360ab23a8f4421

test:
  secret_key_base: a97c565fdda9666545491d17533e703509f2575ba034ed1253cbbed11ce507e2589a32dcbff15ef6f4ec85421b8a20c0d7edca902cd11223d1825860d7eee741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
